### ISSUE TITLE
CodeTest_Roles

### ISSUE THREAD

**Issue by jevinevans** [jevinevans/Game#9]
There is an issue with the way that a single ability is being printed to the screen and printed to a file. It is being worked on.

**Comment by jevyjev324** [comment]
Found out that  the print to file was printing to the wrong file so hoping to fix one error and will see if the ability name issue will resolve itself

**Comment by jevyjev324** [comment]
Need to review, creation and deletion of pointers and try some passing by reference

**Comment by jevinevans** [comment]
Fixe Issue
